### ISSUE TITLE
IdlingResource for Okhttp3 MockWebServer

### ISSUE THREAD

**Issue by kandreadou** [JakeWharton/okhttp-idling-resource#11]
This is a question rather than an issue. Is there a standard way to configure the IdlingResource to work with the OkHttp3 MockWebServer? Hooking it to the client's Dispatcher is not possible as in the regular case. Any guidance would be appreciated.

**Comment by JakeWharton** [comment]
It will not worked wrapped around MockWebServer because the thread that MWS is using to write to the socket is not the same as the one OkHttp (or any HTTP client) is using to read. Thus when MWS is finished sending the response, the client hasn't read it to completion yet.

**Comment by kandreadou** [comment]
Thank you for your response.
