### ISSUE TITLE
Not compatible with retrofit1-okhttp3-client

### ISSUE THREAD

**Issue by rocboronat** [JakeWharton/okhttp-idling-resource#12]
When using `retrofit1-okhttp3-client` with `okhttp-idling-resource`, the IdlingResource lanches a `NoSuchMethodError`. It seems that the OkHttpClient doesn't have the `setIdleCallback()` method.

```java
java.lang.NoSuchMethodError: okhttp3.Dispatcher.setIdleCallback
at com.jakewharton.espresso.OkHttp3IdlingResource.<init>(OkHttp3IdlingResource.java:45)
at com.jakewharton.espresso.OkHttp3IdlingResource.create(OkHttp3IdlingResource.java:35)
at com.anuntis.fotocasa.testutils.OkHttpIdlingResourceRule$1.evaluate(OkHttpIdlingResourceRule.java:19)
at com.schibsted.spain.barista.cleardata.ClearFilesRule$1.evaluate(ClearFilesRule.java:20)
at com.schibsted.spain.barista.cleardata.ClearDatabaseRule$1.evaluate(ClearDatabaseRule.java:20)
at com.schibsted.spain.barista.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
...
```

By the way, as I don't know if this is a responsability of `retrofit1-okhttp3-client` or `okhttp-idling-resource`, I'm opening the issue on both projects. Feel free of closing the issue on the project where it doesn't apply.

Thanks for the good work!

**Comment by JakeWharton** [comment]
What version of OkHttp are you using?

**Comment by rocboronat** [comment]
@JakeWharton just the last version of `retrofit1-okhttp3-client`.

**Comment by JakeWharton** [comment]
But what version of OkHttp itself is being pulled in? You need to have at least version 3.4.0 or newer for the `setIdleCallback` method.

**Comment by rocboronat** [comment]
Actually, I didn't put any other dependency. Just `retrofit1-okhttp3-client`. I guess that `retrofit1-okhttp3-client` depends on http client or something like that...?

**Comment by rocboronat** [comment]
Looking at the pom (https://github.com/JakeWharton/retrofit1-okhttp3-client/blob/master/pom.xml),  it depends on `com.squareup.okhttp3:okhttp:3.2.0`. What do you think about updating the pom to just point a newer version?

**Comment by JakeWharton** [comment]
Hmm this project depends on 3.6.0 though, so your build system should be reconciling the two to the newer version.

If it doesn't or isn't, then you can add an explicit dependency on the latest version OkHttp directly (3.8.1). In practice you should be doing this anyway since there's important bug fixes in the newer versions and you shouldn't rely on adapters like this project or the Retrofit one to keep up-to-date with the releases.

**Comment by rocboronat** [comment]
Ok! I'll do that. Thanks for the support, @JakeWharton !

**Comment by rocboronat** [comment]
Just for the information: it worked :·)
