### ISSUE TITLE
Update to Espresso 3.0 IdlingRegistry

### ISSUE THREAD

**Issue by bootstraponline** [JakeWharton/okhttp-idling-resource#13]
> IdlingRegistry is a lightweight registry that doesn't bring in the entire Espresso library, so you can more easily register resources from your application code. When combining this API with Multiprocess Espresso, you can register idling resources from any process within your application code.
>
>Registration from the Espresso class is now deprecated.
>
> https://android-developers.googleblog.com/2017/07/android-testing-support-library-10-is.html

- https://developer.android.com/reference/android/support/test/espresso/IdlingRegistry.html

**Comment by JakeWharton** [comment]
Want to send a PR?

**Comment by bootstraponline** [comment]
It looks like there are some bugs in the new implementation.

- https://issuetracker.google.com/issues/65624788

Probably better to wait until they're addressed.

**Comment by JakeWharton** [comment]
I don't think that blocks any work being done here though.

**Comment by bootstraponline** [comment]
It doesn't block the work, however updating to use a broken API isn't as appealing.

**Comment by JakeWharton** [comment]
The released version of this library isn't going anywhere. We're only
turning off new users who are already using 3.0 by not updating.

**Comment by bootstraponline** [comment]
That's a good point.
