### ISSUE TITLE
Cannot resolve symbol OkHttp3IdlingResource

### ISSUE THREAD

**Issue by staroflead** [JakeWharton/okhttp-idling-resource#14]
Hello, I just started using expresso for UI testing and I found your interesting library.
I tried to add this library to gradle but it kept failing with this error:

> Error:Conflict with dependency 'com.squareup.okhttp3:okhttp' in project ':app'. Resolved versions for app (3.6.0) and test app (3.4.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

Thanks to ./gradlew :app:dependencies, I can see the source of the conflict is this dependency:

> compile 'com.squareup.retrofit2:converter-gson:2.1.0'

which i tried to resolve config by excluding okhttp3:okhttp:
```
    androidTestCompile 'com.jakewharton.espresso:okhttp3-idling-resource:1.0.0',{
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
```
And gradle ran successfully. However, when I add this line:
`IdlingResource resource = OkHttp3IdlingResource.create("OkHttp", client);`
IDE said **Cannot resolve symbol OkHttp3IdlingResource** and suggest me to add library to classpath

> ad library 'okhttp3-idling-resource-1.0.0' to classpath

I am at a loss at what to do next. Can you help?

**Edit:**

I tried to replace **androidTestCompile** with **compile** without excluding anything and it worked. I was able to import the class properly from com.jakewharton.espresso.OkHttp3IdlingResource;

However there must be a reason for using androidTestCompile ( im still new at android testing), so I dont think what i have done is Ok, right?

**Comment by JakeWharton** [comment]
If the versions between the app and test differ you need to use a [`ResolutionStrategy` in Gradle][1] to choose a single version. Something like this: https://github.com/JakeWharton/u2020/blob/master/build.gradle#L105-L112

Or you can just add an explicit `compile` dependency on OkHttp 3.6.0

 [1]: https://docs.gradle.org/4.1/dsl/org.gradle.api.artifacts.ResolutionStrategy.html
