### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by bootstraponline** [JakeWharton/okhttp-idling-resource#18]
- https://developer.android.com/training/testing/release-notes

![image](https://user-images.githubusercontent.com/1173057/46269447-4786d480-c50f-11e8-8dc4-95240fbcf842.png)

okhttp idling resource isn't compatible with AndroidX due to the package name change.

**Comment by JakeWharton** [comment]
Are you using Jetifier?

**Comment by bootstraponline** [comment]
I'm not. We're only using AndroidX for testing at this point so that seems like overkill. I copied the code locally into our repo and renamed the package.

**Comment by JakeWharton** [comment]
Ok then I don't think there's really any action to take since Jetifier handles this automatically. In the future we'll migrate to AndroidX but it's not a pressing concern because of Jetifier.

**Comment by navczydev** [comment]
I am having same issue even enabled jetifier
