### ISSUE TITLE
testCompile vs compile

### ISSUE THREAD

**Issue by jpshelley** [JakeWharton/okhttp-idling-resource#3]
Maybe this isn't an issue but without a sample its hard to tell.

Should the dependency mainly be used in testing via `testCompile`/`androidTestCompile` or is the idling resource created in production code?
(I've seen differing opinions on using an idling resource in production vs test code so wasn't quite sure how this was to be implemented)

**Comment by JakeWharton** [comment]
Yeah it should be `androidTestCompile`. Want to send a PR?
