### ISSUE TITLE
Tips on using this for requests kicked off in onCreate?

### ISSUE THREAD

**Issue by cxzhang2** [JakeWharton/okhttp-idling-resource#5]
Great use of the new IdleCallback Jake!  Trying to replace my ugly `GlobalEspressoIdlingResources` with it an running into one issue:  I'm using Dagger to inject (a fresh instance) of OkHttpClient in my Activity's onCreate().  Problem is, later on in onCreate() I fire off a request to the webservice, and this request obviously happens before I can grab the OkHttpClient and wrap it in `OkHttp3IdlingResource` / register it with Espresso.   Is there any way to adapt this pattern to my use case?

Thanks!

**Comment by bryant1410** [comment]
I think this question should be placed in StackOverflow. But why are you using a fresh instance of `OkHttpClient`? You should reuse the same one. Also, you can register the idling resource once in `callApplicationOnCreate` in the `TestRunner`, after calling super.

**Comment by cxzhang2** [comment]
Agreed that this probably should go on stackoverflow, so I'll close.

As far as why I pass in fresh instances of the OkHttp client, I have many different dagger scopes and don't have singletons associated with each.  Maybe that's bad practice, but I was looking for a way in general to hook into an activity / fragment's lifecycle during functional testing.  There's the option of registerActivityLifecycleCallbacks for Activities but Fragments are a bit trickier.

**Comment by JakeWharton** [comment]
You should definitely use a single OkHttpClient over multiple. Otherwise
they can't share resources like thread pools and have to create their own.
