### ISSUE TITLE
Junit rule

### ISSUE THREAD

**Issue by yairkukielka** [JakeWharton/okhttp-idling-resource#7]
Hi, could it be interesting to add a rule to this library? It could make it even easier for it to be used. I created an example here: https://github.com/yairkukielka/okhttp-idling-resource/blob/master/src/main/java/com/jakewharton/espresso/OkHttp3IdlingResourceRule.java

Example of usage in a project: https://github.com/yairkukielka/AndroidInstrumentationTests/blob/master/app/src/androidTest/java/com/example/androidinstrumentationtests/MainActivityTest.java

**Comment by JakeWharton** [comment]
Why would you do this instead of registering it just once for the entire
test run?

**Comment by yairkukielka** [comment]
It's just convenience, nothing more.

**Comment by JakeWharton** [comment]
I don't think it's a good idea since you need to install it on every test
and you therefore need access to the OkHttpClient in every test.
